### ISSUE TITLE
Error: Cannot find module 'winston'

### ISSUE THREAD

**Issue by emil1302** [DarkThunder99/Bot-with-Advanced-Dashboard#4]
 node shard.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'winston'
Require stack:
- /home/runner/Bot-with-Advanced-Dashboard-1/utils/logger.js
- /home/runner/Bot-with-Advanced-Dashboard-1/shard.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/Bot-with-Advanced-Dashboard-1/utils/logger.js:1:46)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/Bot-with-Advanced-Dashboard-1/utils/logger.js',
    '/home/runner/Bot-with-Advanced-Dashboard-1/shard.js'
  ]
}
exit status 1

**Comment by M4riosDev** [comment]
download discord.js

**Comment by Relism** [comment]
run "npm install or npm i" in your terminal while being in the root directory of your bot (the directory with all the files).

**Comment by eYuM-coder** [comment]
run the bot normally, and the project will handle the rest.
